ALTER TABLE prosecutor ADD COLUMN age INT;
ALTER TABLE prosecutor ADD COLUMN sex VARCHAR DEFAULT 'Male';
ALTER TABLE prosecutor ADD COLUMN birthday VARCHAR;
ALTER TABLE prosecutor ADD COLUMN id_number VARCHAR;
ALTER TABLE prosecutor ADD COLUMN experience VARCHAR;